base_model_dir: ???
warmup_epochs: 10
pretrain_epochs: 0
epochs: 250
save_freq: 25
monitor_freq: 10

encoder:
  init_lr: 1e-05
  lr: 5e-04
  method: "Adam"
  momentum: 0.0
  weight_decay: 1e-06
  scheduler:
      decay_factor: 0.85
      threshold: 10
      patience: 10
      method: "Plateau"
decoder:
  init_lr: 1e-05
  lr: 1e-02
  method: "RSGD"
  momentum: 0.0
  weight_decay: 0.0
  scheduler:
      decay_factor: 0.85
      threshold: 10
      patience: 20
      method: "Plateau"

dataloader:
    batch_size: 16
    slices_with_mask: true
    prefetch_factor: 3
