# @package _global_

data:
  path: /path/to/data
  random_train_val_split: False
  batch_size: 1024
  num_workers: 0

network:
  _target_: cerm.examples.stiefel.network.resnet.WideResNet
  input_dim: [3, 32, 32]
  num_kernels: [16, 32, 32] 
  widen_factor: 1
  num_res_blocks: 1
  num_classes: 10
  stiefel: True
  
unconstrained_optimizer:
  _target_: torch.optim.Adam
  lr: 1e-02
  weight_decay: 0.0005

constrained_optimizer:
  _target_: cerm.optimizer.riemannian_sgd.RSGD
  lr: 1e-02

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: "min"
  factor: 0.75
  threshold: 0.01
  patience: 7
  verbose: True

loss:
  _target_: torch.nn.CrossEntropyLoss

training:
  epochs: 100
  log_interval: 10