max_num_aug: 4
transforms: []
shift:
    x: [-48, 48]
    y: [-48, 48]
rotate:
    angle: [-0.1, 0.1]
shear:
    axis: "horizontal"
    factor: [-0.05, 0.05]
scale:
    factor: [0.75, 1.3]
crop:
    midpt_x: [128, 128]
    midpt_y: [128, 128]
    area: [0.85, 0.95]
elastic:
    grid_field: [128, 128]
    mean_field: [0.0, 0.0]
    sigma_field: [5.0, 5.0]
    sigma_mollifier: [1.65, 1.65]
    int_time: 1.0
noise:
    type: "gaussian"
    loc: 0.0
    scale: 5e-05
blur:
    sigma_x: [0.55, 0.95]
    sigma_y: [0.55, 0.95]
color_jitter:
    brightness: [0.0, 1.0]
    contrast: [0.0, 1.0]
    saturation: [0.0, 1.0]
    hue: [-0.5, 0.5]



