max_num_aug: 4
transforms: ["shift", "rotate", "shear", "crop", "elastic", "noise", "blur", "scale"]
shift:
    x: [-32, 32]
    y: [-32, 32]
rotate:
    angle: [-0.05, 0.05]
shear:
    axis: "horizontal"
    factor: [-0.05, 0.05]
scale:
    factor: [0.75, 1.3]
crop:
    midpt_x: [80, 110]
    midpt_y: [80, 110]
    area: [0.85, 0.95]
elastic:
    grid_field: [96, 96]
    mean_field: [0.0, 0.0]
    sigma_field: [5.0, 5.0]
    sigma_mollifier: [1.65, 1.65]
    int_time: 0.5
noise:
    type: "gaussian"
    loc: 0.0
    scale: 1e-05
blur:
    sigma_x: [0.55, 0.95]
    sigma_y: [0.55, 0.95]
color_jitter:
    brightness: [0.0, 1.0]
    contrast: [0.0, 1.0]
    saturation: [0.0, 1.0]
    hue: [-0.5, 0.5]
