# @package _global_
defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/launcher: submitit_slurm

hydra:
  sweeper:
    sampler:
      seed: 42
    direction: maximize
    study_name: mra_bayesian_search
    storage: null
    n_trials: 600
    n_jobs: 10
    max_failure_rate: 1.
    # `custom_search_space` should be a dotpath pointing to a
    # callable that provides search-space configuration logic:
    custom_search_space: mra.pnp_hyperparam.search_space.configure
