activation: GELU

encoder:
  len_encoder: 6
  len_res_block: 3
  init_num_kernels: 32

decoder:
  order_wavelet: 4
  init_res_level: 7
  num_levels_down: 3
  num_levels_up: 3
  num_channels_compress: 8

mlp_contour:
  depth: 3
  dim_latent: 124

regularization:
  dropout_prob: 0.0
  group_norm: true
  num_groups: 8
